import { FileExtensionData, FileCategory } from './types';

export const FILE_DATABASE: FileExtensionData[] = [
  // --- VALVE / GAMES ---
  {
    ext: '.vpk',
    name: 'Valve Pak',
    category: FileCategory.GAME,
    description: 'Основной формат архивов движка Source (Half-Life 2, Dota 2, CS2).',
    fullDescription: 'VPK (Valve Pak) — это формат пакетов, используемый движком Source для хранения содержимого игры (текстур, моделей, звуков). Пришел на смену формату GCF. Позволяет игре быстро искать и загружать тысячи мелких файлов. Поддерживает разбивку на несколько частей (dir, 001, 002...) для обхода ограничений файловой системы.\n\nВАЖНАЯ ИНФОРМАЦИЯ ОТ РАЗРАБОТЧИКОВ:\n1) Half-life 3 выйдет завтра\n2) Если half-life 3 не вышла прочитайте первый пункт',
    osCompatibility: ['Windows', 'Linux', 'macOS (Steam)'],
    technologies: ['Source Engine', 'Directory Structure', 'Preloading'],
    pros: ['Быстрое чтение ресурсов', 'Модульность модов', 'Целостность данных'],
    cons: ['Требует GCFScape для открытия', 'Проприетарный формат'],
    popularity: 90
  },
  {
    ext: '.bsp',
    name: 'Binary Space Partition',
    category: FileCategory.GAME,
    description: 'Скомпилированная карта уровня (GoldSrc, Source, Quake).',
    fullDescription: 'Формат файлов карт, использующий метод двоичного разбиения пространства (BSP). Хранит геометрию уровня, освещение (lightmaps) и физические коллизии. Используется в Quake, Half-Life, CS 1.6, CS:GO. Это "готовый" уровень, оптимизированный для рендеринга видеокартой.\n\nПРИМЕЧАНИЕ:\n1) Half-life 3 выйдет завтра\n2) Если half-life 3 не вышла прочитайте первый пункт',
    osCompatibility: ['Windows', 'Linux', 'macOS'],
    technologies: ['Binary Space Partitioning', 'PVS (Potential Visibility Set)', 'Lightmaps'],
    pros: ['Высокая производительность рендеринга', 'Запеченное освещение'],
    cons: ['Нельзя редактировать геометрию (нужен декомпил)', 'Долгое время компиляции'],
    popularity: 85
  },
  {
    ext: '.vmf',
    name: 'Valve Map Format',
    category: FileCategory.GAME,
    description: 'Исходный файл карты для редактора Hammer.',
    fullDescription: 'Текстовый формат, хранящий "сырую" геометрию карты до компиляции. Внутри выглядит как структурированный текст (Key-Value), описывающий браши, энтити и текстуры. Именно здесь создаются уровни для CS и HL.\n\nСЛУЖЕБНОЕ СООБЩЕНИЕ:\n1) Half-life 3 выйдет завтра\n2) Если half-life 3 не вышла прочитайте первый пункт',
    osCompatibility: ['Windows (Hammer Editor)'],
    technologies: ['Key-Value Data', 'Hammer Editor'],
    pros: ['Человекочитаемый формат', 'Полное редактирование'],
    cons: ['Не открывается игрой (требует компиляции в BSP)'],
    popularity: 40
  },
  {
    ext: '.mdl',
    name: 'Model Data File',
    category: FileCategory.GAME,
    description: '3D-модель персонажа или предмета в играх Valve.',
    fullDescription: 'Скомпилированная модель движка Source. Содержит сетку (mesh), анимации, скелет и привязку к физике. Часто идет в комплекте с файлами .vtx (оптимизация) и .vvd (вершины).\n\nСТАТУС ПРОЕКТА:\n1) Half-life 3 выйдет завтра\n2) Если half-life 3 не вышла прочитайте первый пункт',
    osCompatibility: ['Windows', 'Linux', 'macOS'],
    technologies: ['Skeletal Animation', 'LOD (Level of Detail)', 'Hitboxes'],
    pros: ['Оптимизация под движок', 'Сложная физика (Ragdoll)'],
    cons: ['Сложный пайплайн экспорта из Blender/Maya'],
    popularity: 75
  },
  {
    ext: '.dem',
    name: 'Source Engine Demo',
    category: FileCategory.GAME,
    description: 'Запись игрового процесса (реплей) в CS и Dota.',
    fullDescription: 'Файл "демки". Это не видеозапись, а лог всех сетевых пакетов и событий матча. Позволяет при воспроизведении летать камерой, менять скорость и смотреть от лица любого игрока. Весит в 100 раз меньше видео.\n\nПРОГНОЗ:\n1) Half-life 3 выйдет завтра\n2) Если half-life 3 не вышла прочитайте первый пункт',
    osCompatibility: ['Windows', 'Linux', 'macOS'],
    technologies: ['Network Tick Recording', 'Delta Compression'],
    pros: ['Абсолютная точность воспроизведения', 'Малый вес', 'Анализ данных'],
    cons: ['Перестает работать после обновления игры'],
    popularity: 80
  },

  // --- IMAGES ---
  {
    ext: '.png',
    name: 'Portable Network Graphics',
    category: FileCategory.IMAGE,
    description: 'Растровый формат сжатия без потерь. Стандарт для веба и графики с прозрачностью.',
    fullDescription: 'PNG — один из самых популярных растровых форматов. Ключевая особенность — поддержка альфа-канала (прозрачности). Использует алгоритм Deflate (без потерь), качество не ухудшается при сохранении. Идеален для логотипов и интерфейсов.',
    osCompatibility: ['Все ОС', 'Web'],
    technologies: ['Deflate', 'Alpha Channel', 'Interlacing'],
    pros: ['Прозрачность', 'Нет потерь качества', 'Универсальность'],
    cons: ['Больше вес чем у JPG'],
    popularity: 98
  },
  {
    ext: '.jpg',
    name: 'JPEG Image',
    category: FileCategory.IMAGE,
    description: 'Стандарт для фотографий. Сжатие с потерями.',
    fullDescription: 'JPEG использует дискретное косинусное преобразование для удаления деталей, невидимых глазу. Идеален для фото, но плох для чертежей и текста из-за артефактов.',
    osCompatibility: ['Все ОС', 'Камеры', 'Web'],
    technologies: ['DCT', 'Lossy Compression', 'EXIF'],
    pros: ['Малый размер', 'Совместимость 100%'],
    cons: ['Артефакты сжатия', 'Нет прозрачности'],
    popularity: 99
  },
  {
    ext: '.webp',
    name: 'Web Picture',
    category: FileCategory.IMAGE,
    description: 'Формат от Google. Легче JPG и PNG на 30%.',
    fullDescription: 'Современный стандарт веба. Поддерживает и сжатие с потерями, и без, и прозрачность, и анимацию. Заменяет собой сразу JPG, PNG и GIF.',
    osCompatibility: ['Android', 'Web', 'Modern OS'],
    technologies: ['VP8 Keyframes', 'Predictive Coding'],
    pros: ['Лучшее сжатие', 'Универсальность функций'],
    cons: ['Не открывается на старых системах'],
    popularity: 85
  },
  {
    ext: '.svg',
    name: 'Scalable Vector Graphics',
    category: FileCategory.IMAGE,
    description: 'Векторная графика. Бесконечное масштабирование.',
    fullDescription: 'XML-файл, описывающий линии и фигуры математически. Можно растянуть хоть на небоскреб без пикселей. Поддерживает CSS и JS анимацию.',
    osCompatibility: ['Web', 'Design Software'],
    technologies: ['XML', 'Vector Math', 'DOM'],
    pros: ['Масштабируемость', 'Малый вес (текст)', 'Интерактивность'],
    cons: ['Сложно для фотореализма'],
    popularity: 90
  },
  {
    ext: '.gif',
    name: 'Graphics Interchange Format',
    category: FileCategory.IMAGE,
    description: 'Анимации и мемы. 256 цветов.',
    fullDescription: 'Старейший формат анимации. Ограничен палитрой в 256 цветов, что делает его плохим для видео, но идеальным для простых петель и мемов.',
    osCompatibility: ['Universal'],
    technologies: ['LZW', 'Indexed Color', 'Animation'],
    pros: ['Простота анимации', 'Работает везде'],
    cons: ['Мало цветов', 'Большой вес'],
    popularity: 92
  },
  {
    ext: '.bmp',
    name: 'Bitmap Image File',
    category: FileCategory.IMAGE,
    description: 'Несжатое растровое изображение от Microsoft.',
    fullDescription: 'Классический формат Windows. Хранит пиксели "как есть", без сжатия (обычно). Файлы огромные, но читаются любым утюгом.',
    osCompatibility: ['Windows', 'Universal'],
    technologies: ['Uncompressed Raster', 'RLE (редко)'],
    pros: ['Мгновенное чтение', 'Простота структуры'],
    cons: ['Гигантский размер'],
    popularity: 30
  },
  {
    ext: '.tiff',
    name: 'Tagged Image File Format',
    category: FileCategory.IMAGE,
    description: 'Формат для полиграфии и сканирования.',
    fullDescription: 'Профессиональный стандарт для печати. Поддерживает слои, CMYK, глубину цвета 32 бита и сжатие без потерь. Используется фотографами и типографиями.',
    osCompatibility: ['macOS', 'Windows', 'Printers'],
    technologies: ['Layers', 'CMYK', 'LZW/ZIP'],
    pros: ['Высочайшее качество', 'Метаданные'],
    cons: ['Не для веба', 'Большой вес'],
    popularity: 50
  },
  {
    ext: '.raw',
    name: 'Raw Image Data',
    category: FileCategory.IMAGE,
    description: 'Цифровой негатив с матрицы камеры.',
    fullDescription: 'Сырые данные с сенсора фотоаппарата. Требует "проявки" (конвертации). Позволяет менять экспозицию и баланс белого после съемки без потери качества.',
    osCompatibility: ['Photo Software (Lightroom)'],
    technologies: ['Bayer Filter', '12-14 bit color'],
    pros: ['Максимум информации', 'Гибкость обработки'],
    cons: ['Нужен спец. софт', 'Разный у всех камер (CR2, NEF, ARW)'],
    popularity: 60
  },
  {
    ext: '.ico',
    name: 'Icon File',
    category: FileCategory.IMAGE,
    description: 'Иконки для Windows и сайтов (favicon).',
    fullDescription: 'Контейнер, хранящий одно изображение в нескольких разрешениях (16x16, 32x32, 256x256). Позволяет системе выбирать нужный размер.',
    osCompatibility: ['Windows', 'Web'],
    technologies: ['Multi-resolution container'],
    pros: ['Адаптивность размера'],
    cons: ['Устаревает (заменяется PNG/SVG)'],
    popularity: 70
  },

  // --- AUDIO ---
  {
    ext: '.mp3',
    name: 'MPEG Audio Layer III',
    category: FileCategory.AUDIO,
    description: 'Самый популярный аудиоформат в мире.',
    fullDescription: 'Легендарный формат сжатия с потерями. Удалил "лишние" звуки и сделал музыку доступной в интернете.',
    osCompatibility: ['Universal'],
    technologies: ['Psychoacoustics', 'Huffman coding'],
    pros: ['Совместимость 100%', 'Малый размер'],
    cons: ['Потери качества'],
    popularity: 100
  },
  {
    ext: '.wav',
    name: 'Waveform Audio',
    category: FileCategory.AUDIO,
    description: 'Несжатый студийный звук.',
    fullDescription: 'Точная копия аналоговой волны. Используется профи для записи и мастеринга. 10 МБ за минуту.',
    osCompatibility: ['Universal'],
    technologies: ['PCM (Pulse Code Modulation)'],
    pros: ['Идеальное качество', 'Легкий монтаж'],
    cons: ['Огромный размер'],
    popularity: 65
  },
  {
    ext: '.flac',
    name: 'Free Lossless Audio Codec',
    category: FileCategory.AUDIO,
    description: 'Сжатие без потерь качества.',
    fullDescription: 'Архиватор для звука. Сжимает файл в 2 раза, но при распаковке восстанавливает каждый бит оригинала. Выбор аудиофилов.',
    osCompatibility: ['Hi-Fi Players', 'Android', 'Windows'],
    technologies: ['Linear Prediction', 'Lossless'],
    pros: ['Качество 1:1', 'Метаданные'],
    cons: ['Тяжелее MP3'],
    popularity: 60
  },
  {
    ext: '.aac',
    name: 'Advanced Audio Coding',
    category: FileCategory.AUDIO,
    description: 'Стандарт Apple и YouTube. Лучше MP3.',
    fullDescription: 'Преемник MP3. При том же размере файла дает заметно более чистый звук, особенно на высоких частотах. Стандарт для iPhone, iTunes и YouTube.',
    osCompatibility: ['iOS', 'Android', 'Web', 'Windows'],
    technologies: ['MDCT', 'TNS', 'SBR'],
    pros: ['Эффективнее MP3', 'Стандарт стриминга'],
    cons: ['Менее "народный" чем MP3'],
    popularity: 88
  },
  {
    ext: '.ogg',
    name: 'Ogg Vorbis',
    category: FileCategory.AUDIO,
    description: 'Свободный формат, популярен в играх.',
    fullDescription: 'Полностью бесплатный и открытый аналог MP3/AAC. Часто используется в играх (Minecraft) и Spotify (мобильном) из-за отсутствия лицензионных отчислений.',
    osCompatibility: ['Android', 'PC', 'Linux'],
    technologies: ['Vorbis', 'Container'],
    pros: ['Бесплатный', 'Качественный'],
    cons: ['Не играет на iPhone (нативно)'],
    popularity: 55
  },
  {
    ext: '.m4a',
    name: 'MPEG-4 Audio',
    category: FileCategory.AUDIO,
    description: 'Аудио-контейнер для AAC или ALAC.',
    fullDescription: 'Файл MP4, содержащий только звук. Обычно внутри кодек AAC (с потерями) или ALAC (Apple Lossless). Родной формат для диктофонов Apple.',
    osCompatibility: ['Apple Ecosystem', 'Windows'],
    technologies: ['MPEG-4 Part 14', 'AAC/ALAC'],
    pros: ['Высокое качество', 'Поддержка глав'],
    cons: ['Путаница кодеков внутри'],
    popularity: 75
  },
  {
    ext: '.mid',
    name: 'Musical Instrument Digital Interface',
    category: FileCategory.AUDIO,
    description: 'Ноты, а не звук. Весит килобайты.',
    fullDescription: 'MIDI не содержит звука. Это набор команд для синтезатора: "нажми ноту Ля на 2 секунды пианино". Благодаря этому файлы весят копейки, но звучат по-разному на разных устройствах.',
    osCompatibility: ['Synthesizers', 'DAW', 'Windows'],
    technologies: ['Note Events', 'Velocity', 'Clock'],
    pros: ['Микроскопический размер', 'Редактирование нот'],
    cons: ['Звучит как "синтезатор 90-х"'],
    popularity: 40
  },

  // --- VIDEO ---
  {
    ext: '.mp4',
    name: 'MPEG-4 Part 14',
    category: FileCategory.VIDEO,
    description: 'Главный видеоформат планеты.',
    fullDescription: 'Универсальный контейнер. Поддерживается всем: от кнопочных телефонов до 8K телевизоров. Обычно содержит видео H.264 и звук AAC.',
    osCompatibility: ['Universal'],
    technologies: ['H.264', 'H.265', 'Streaming'],
    pros: ['Совместимость', 'Баланс качества'],
    cons: ['Ограниченные возможности субтитров'],
    popularity: 100
  },
  {
    ext: '.mkv',
    name: 'Matroska',
    category: FileCategory.VIDEO,
    description: 'Контейнер для киноманов и пиратов.',
    fullDescription: 'Позволяет упаковать в один файл фильм, 10 озвучек и 20 субтитров. Поддерживает любые кодеки. Стандарт для сериалов и Blu-ray рипов.',
    osCompatibility: ['PC', 'Android', 'Smart TV'],
    technologies: ['EBML', 'Soft Subs', 'Chapters'],
    pros: ['Гибкость', 'Все-в-одном'],
    cons: ['Плохая поддержка в браузерах'],
    popularity: 80
  },
  {
    ext: '.avi',
    name: 'Audio Video Interleave',
    category: FileCategory.VIDEO,
    description: 'Старый добрый формат из 90-х.',
    fullDescription: 'Разработан Microsoft в 1992. Технически устарел, не поддерживает современные фишки (меню, потоковое видео), но все еще встречается в старых архивах.',
    osCompatibility: ['Windows', 'Legacy players'],
    technologies: ['RIFF', 'VFW'],
    pros: ['Читается старыми DVD-плеерами'],
    cons: ['Огромный размер', 'Нет поддержки H.265'],
    popularity: 50
  },
  {
    ext: '.mov',
    name: 'QuickTime Movie',
    category: FileCategory.VIDEO,
    description: 'Формат для iPhone и монтажа на Mac.',
    fullDescription: 'Родной формат Apple. Часто используется в профессиональном видеопроизводстве (ProRes) из-за высокого качества.',
    osCompatibility: ['macOS', 'iOS', 'Windows'],
    technologies: ['ProRes', 'HEVC', 'Alpha Channel'],
    pros: ['Прозрачный фон', 'Качество монтажа'],
    cons: ['Тяжелый вес'],
    popularity: 70
  },
  {
    ext: '.webm',
    name: 'Web Media',
    category: FileCategory.VIDEO,
    description: 'Видео для HTML5. Легкое и прозрачное.',
    fullDescription: 'Создан Google специально для YouTube и веба. Открытый, бесплатный, поддерживает прозрачность в браузере. Обычно кодек VP9 или AV1.',
    osCompatibility: ['Browsers', 'Android'],
    technologies: ['VP9', 'AV1', 'Vorbis/Opus'],
    pros: ['Бесплатный', 'Прозрачность в вебе'],
    cons: ['Не работает в старых Safari'],
    popularity: 65
  },
  {
    ext: '.flv',
    name: 'Flash Video',
    category: FileCategory.VIDEO,
    description: 'Умерший стандарт Flash-плеера.',
    fullDescription: 'Когда-то все видео в интернете было FLV. Смерть Flash Player убила и этот формат. Сейчас встречается только в старых архивах.',
    osCompatibility: ['Legacy'],
    technologies: ['Sorenson Spark', 'VP6'],
    pros: ['История интернета'],
    cons: ['Устарел', 'Небезопасен'],
    popularity: 10
  },

  // --- DOCUMENTS ---
  {
    ext: '.pdf',
    name: 'Portable Document Format',
    category: FileCategory.DOCUMENT,
    description: 'Цифровая бумага. Выглядит везде одинаково.',
    fullDescription: 'Стандарт для договоров, книг и чертежей. Фиксирует верстку намертво. Содержит текст, векторы, растр, шрифты и формы.',
    osCompatibility: ['Universal'],
    technologies: ['PostScript', 'Layers', 'Encryption'],
    pros: ['Неизменность', 'Векторное качество'],
    cons: ['Трудно редактировать'],
    popularity: 98
  },
  {
    ext: '.docx',
    name: 'Word Document',
    category: FileCategory.DOCUMENT,
    description: 'Стандартный офисный документ.',
    fullDescription: 'XML-файлы в ZIP-архиве. Современный формат Microsoft Word. Поддерживает сложную верстку, рецензирование и макросы.',
    osCompatibility: ['Windows', 'macOS', 'Mobile'],
    technologies: ['Open XML', 'ZIP container'],
    pros: ['Индустриальный стандарт'],
    cons: ['Платный Office для полной совместимости'],
    popularity: 96
  },
  {
    ext: '.xlsx',
    name: 'Excel Spreadsheet',
    category: FileCategory.DOCUMENT,
    description: 'Таблицы, формулы и финансы.',
    fullDescription: 'Мощнейший инструмент для работы с данными. Поддерживает миллионы строк, скрипты VBA и сложные вычисления.',
    osCompatibility: ['Universal Office'],
    technologies: ['Calculation Engine', 'Pivot Tables'],
    pros: ['Мощь вычислений'],
    cons: ['Тяжелый на больших данных'],
    popularity: 95
  },
  {
    ext: '.pptx',
    name: 'PowerPoint Presentation',
    category: FileCategory.DOCUMENT,
    description: 'Слайды и презентации.',
    fullDescription: 'Формат для публичных выступлений. Поддерживает анимацию переходов, встроенное видео и заметки докладчика.',
    osCompatibility: ['Universal Office'],
    technologies: ['Slide Master', 'Transitions'],
    pros: ['Визуализация идей'],
    cons: ['Часто делают "скучные" слайды'],
    popularity: 90
  },
  {
    ext: '.txt',
    name: 'Plain Text',
    category: FileCategory.DOCUMENT,
    description: 'Просто текст. Ничего лишнего.',
    fullDescription: 'Самый простой и надежный формат. Только символы. Читается на любом компьютере с 1970 года.',
    osCompatibility: ['Universal'],
    technologies: ['ASCII', 'UTF-8'],
    pros: ['Вечность', 'Малый вес'],
    cons: ['Нет форматирования'],
    popularity: 88
  },
  {
    ext: '.rtf',
    name: 'Rich Text Format',
    category: FileCategory.DOCUMENT,
    description: 'Текст с простым оформлением.',
    fullDescription: 'Старый формат от Microsoft для обмена текстом с форматированием (жирный, курсив, шрифты) между разными программами.',
    osCompatibility: ['Windows', 'macOS'],
    technologies: ['Markup tags'],
    pros: ['Встроен во все редакторы'],
    cons: ['Устарел', 'Большой вес'],
    popularity: 40
  },
  {
    ext: '.csv',
    name: 'Comma-Separated Values',
    category: FileCategory.DOCUMENT,
    description: 'Таблица в текстовом виде.',
    fullDescription: 'Простейшая база данных. Строки - записи, запятые - разделители колонок. Читается и Блокнотом, и Excel, и любым языком программирования.',
    osCompatibility: ['Universal'],
    technologies: ['Delimiters', 'Plain Text'],
    pros: ['Идеален для импорта/экспорта данных'],
    cons: ['Проблемы с кавычками и запятыми в тексте'],
    popularity: 85
  },
  {
    ext: '.md',
    name: 'Markdown',
    category: FileCategory.DOCUMENT,
    description: 'Текст для документации разработчиков.',
    fullDescription: 'Облегченный язык разметки. Позволяет писать форматированный текст, используя простые символы (# Заголовок, **жирный**). Стандарт для README на GitHub.',
    osCompatibility: ['Developers', 'Web'],
    technologies: ['Lightweight Markup'],
    pros: ['Пишется быстро', 'Конвертируется в HTML'],
    cons: ['Нужен вьюер для красоты'],
    popularity: 92
  },

  // --- ARCHIVES ---
  {
    ext: '.zip',
    name: 'ZIP Archive',
    category: FileCategory.ARCHIVE,
    description: 'Базовый архиватор. Есть везде.',
    fullDescription: 'Самый совместимый формат архивов. Windows и macOS открывают его без программ. Сжатие среднее, скорость высокая.',
    osCompatibility: ['Universal'],
    technologies: ['DEFLATE', 'CRC32'],
    pros: ['Работает из коробки'],
    cons: ['Не лучшее сжатие'],
    popularity: 99
  },
  {
    ext: '.rar',
    name: 'Roshal Archive',
    category: FileCategory.ARCHIVE,
    description: 'Отличное сжатие и восстановление.',
    fullDescription: 'Формат Евгения Рошала. Умеет восстанавливать битые файлы и разбивать архивы на части. Сжимает лучше ZIP.',
    osCompatibility: ['Windows (WinRAR)', 'Android'],
    technologies: ['Solid Compression', 'Recovery Record'],
    pros: ['Надежность', 'Плотность'],
    cons: ['Платный архиватор для создания'],
    popularity: 85
  },
  {
    ext: '.7z',
    name: '7-Zip',
    category: FileCategory.ARCHIVE,
    description: 'Экстремальное сжатие. Бесплатно.',
    fullDescription: 'Открытый формат с алгоритмом LZMA. Сжимает файлы сильнее всех конкурентов, но медленнее упаковывает.',
    osCompatibility: ['Windows', 'Linux'],
    technologies: ['LZMA2', 'AES-256'],
    pros: ['Лучшее сжатие', 'Бесплатно'],
    cons: ['Долгая упаковка'],
    popularity: 80
  },
  {
    ext: '.tar.gz',
    name: 'Gzipped Tarball',
    category: FileCategory.ARCHIVE,
    description: 'Стандарт архивов в Linux.',
    fullDescription: 'Классика Unix. TAR собирает файлы в кучу (без сжатия), а GZIP сжимает эту кучу. Основа распространения софта в Linux.',
    osCompatibility: ['Linux', 'macOS', 'Windows (WSL)'],
    technologies: ['Tar stream', 'Gzip'],
    pros: ['Сохраняет права доступа Unix'],
    cons: ['Неудобен в Windows'],
    popularity: 75
  },
  {
    ext: '.iso',
    name: 'ISO Image',
    category: FileCategory.ARCHIVE,
    description: 'Образ диска (CD/DVD/USB).',
    fullDescription: 'Точная побитовая копия файловой системы оптического диска. Используется для установки ОС и игр.',
    osCompatibility: ['Universal'],
    technologies: ['ISO 9660', 'UDF'],
    pros: ['Монтируется как диск'],
    cons: ['Не сжимает данные'],
    popularity: 88
  },

  // --- EXECUTABLES ---
  {
    ext: '.exe',
    name: 'Windows Executable',
    category: FileCategory.EXECUTABLE,
    description: 'Программа для Windows.',
    fullDescription: 'Файл, который запускает код. Содержит инструкции для процессора, иконки и ресурсы. Сердце Windows.',
    osCompatibility: ['Windows'],
    technologies: ['PE Format', 'x86/x64 Code'],
    pros: ['Нативная скорость'],
    cons: ['Риск вирусов'],
    popularity: 98
  },
  {
    ext: '.apk',
    name: 'Android Package',
    category: FileCategory.EXECUTABLE,
    description: 'Приложение для Android.',
    fullDescription: 'ZIP-архив с байт-кодом Java/Kotlin внутри. Установочный файл для телефонов и планшетов.',
    osCompatibility: ['Android'],
    technologies: ['Dalvik Bytecode', 'Manifest'],
    pros: ['Легкость распространения'],
    cons: ['Легко взломать'],
    popularity: 95
  },
  {
    ext: '.dmg',
    name: 'Disk Image',
    category: FileCategory.EXECUTABLE,
    description: 'Установщик для macOS.',
    fullDescription: 'Образ диска, который красиво монтируется в Finder. Пользователь просто перетаскивает иконку программы в папку Applications.',
    osCompatibility: ['macOS'],
    technologies: ['HFS+/APFS', 'Compression'],
    pros: ['Эстетика и простота'],
    cons: ['Только Mac'],
    popularity: 60
  },
  {
    ext: '.msi',
    name: 'Microsoft Installer',
    category: FileCategory.EXECUTABLE,
    description: 'Корпоративный установщик.',
    fullDescription: 'База данных установки. Позволяет системным администраторам удаленно ставить и удалять софт в офисах.',
    osCompatibility: ['Windows'],
    technologies: ['SQL Database', 'Transactional'],
    pros: ['Чистое удаление', 'Восстановление'],
    cons: ['Сложное создание'],
    popularity: 70
  },

  // --- CODE ---
  {
    ext: '.html',
    name: 'HyperText Markup Language',
    category: FileCategory.CODE,
    description: 'Каркас веб-сайтов.',
    fullDescription: 'Язык разметки, который говорит браузеру, где заголовок, а где кнопка. Основа всего интернета.',
    osCompatibility: ['Web'],
    technologies: ['DOM', 'Tags'],
    pros: ['Простота', 'Фундамент Web'],
    cons: ['Не программирование (нет логики)'],
    popularity: 100
  },
  {
    ext: '.js',
    name: 'JavaScript',
    category: FileCategory.CODE,
    description: 'Логика веба. Делает сайты живыми.',
    fullDescription: 'Язык программирования, работающий в браузере. Анимация, запросы к серверу, интерактивность — это все JS.',
    osCompatibility: ['Web', 'Node.js'],
    technologies: ['ECMAScript', 'JIT'],
    pros: ['Самый популярный язык', 'Вездесущность'],
    cons: ['Хаос в экосистеме (npm)'],
    popularity: 100
  },
  {
    ext: '.css',
    name: 'Cascading Style Sheets',
    category: FileCategory.CODE,
    description: 'Внешний вид сайтов.',
    fullDescription: 'Таблицы стилей. Отвечают за цвета, шрифты, отступы и красоту веб-страниц.',
    osCompatibility: ['Web'],
    technologies: ['Selectors', 'Flexbox/Grid'],
    pros: ['Разделение стиля и контента'],
    cons: ['Сложность поддержки на больших проектах'],
    popularity: 100
  },
  {
    ext: '.py',
    name: 'Python',
    category: FileCategory.CODE,
    description: 'Язык для ИИ и новичков.',
    fullDescription: 'Скриптовый язык с чистым синтаксисом. Король Data Science, нейросетей и автоматизации.',
    osCompatibility: ['Cross-platform'],
    technologies: ['Interpreter', 'Dynamic Typing'],
    pros: ['Читаемость', 'Библиотеки'],
    cons: ['Медленный'],
    popularity: 99
  },
  {
    ext: '.cpp',
    name: 'C++',
    category: FileCategory.CODE,
    description: 'Мощь и скорость. Игры и движки.',
    fullDescription: 'Язык для создания операционных систем, драйверов, игр (Unreal Engine) и высоконагруженных систем. Дает полный контроль над памятью.',
    osCompatibility: ['Cross-platform'],
    technologies: ['Compilation', 'Pointers', 'OOP'],
    pros: ['Максимальная скорость'],
    cons: ['Очень сложный', 'Утечки памяти'],
    popularity: 90
  },
  {
    ext: '.cs',
    name: 'C#',
    category: FileCategory.CODE,
    description: 'Язык Microsoft и Unity.',
    fullDescription: 'Мощный язык для Windows-приложений и разработки игр на движке Unity.',
    osCompatibility: ['Windows', 'Cross-platform (.NET Core)'],
    technologies: ['.NET CLR', 'Garbage Collection'],
    pros: ['Удобство Enterprise', 'Unity'],
    cons: ['Завязан на экосистему MS (раньше)'],
    popularity: 88
  },
  {
    ext: '.java',
    name: 'Java',
    category: FileCategory.CODE,
    description: 'Корпоративный стандарт и Android.',
    fullDescription: 'Язык со строгой типизацией. Работает на любом устройстве, где есть Java Virtual Machine (JVM). Основа старых Android приложений и банковского ПО.',
    osCompatibility: ['Universal (JVM)'],
    technologies: ['JVM', 'Bytecode'],
    pros: ['Надежность', 'Кроссплатформенность'],
    cons: ['Многословный код', 'Потребление памяти'],
    popularity: 92
  },
  {
    ext: '.php',
    name: 'PHP',
    category: FileCategory.CODE,
    description: 'Серверный язык веба.',
    fullDescription: 'На нем работает 70% интернета (WordPress, старый Facebook). Генерирует HTML страницы на сервере.',
    osCompatibility: ['Servers (Linux/Windows)'],
    technologies: ['Server-side scripting'],
    pros: ['Простота деплоя', 'Дешевый хостинг'],
    cons: ['Странный дизайн языка'],
    popularity: 75
  },
  {
    ext: '.json',
    name: 'JSON',
    category: FileCategory.CODE,
    description: 'Данные для обмена.',
    fullDescription: 'Текстовый формат объектов JS. Стандарт передачи данных между сервером и браузером.',
    osCompatibility: ['Universal'],
    technologies: ['Serialization'],
    pros: ['Легкий', 'Читаемый'],
    cons: ['Строгий синтаксис'],
    popularity: 98
  },
  {
    ext: '.sql',
    name: 'Structured Query Language',
    category: FileCategory.CODE,
    description: 'Запросы к базам данных.',
    fullDescription: 'Код для поиска, добавления и изменения информации в базах данных (MySQL, PostgreSQL).',
    osCompatibility: ['Databases'],
    technologies: ['Relational Algebra'],
    pros: ['Стандарт работы с данными'],
    cons: ['Разные диалекты'],
    popularity: 90
  },
  {
    ext: '.go',
    name: 'Go (Golang)',
    category: FileCategory.CODE,
    description: 'Язык от Google для облаков.',
    fullDescription: 'Простой, быстрый, компилируемый. Создан для написания серверов и микросервисов, выдерживающих огромные нагрузки.',
    osCompatibility: ['Cross-platform'],
    technologies: ['Goroutines', 'Garbage Collection'],
    pros: ['Скорость', 'Параллелизм'],
    cons: ['Специфическая обработка ошибок'],
    popularity: 80
  },
  {
    ext: '.rs',
    name: 'Rust',
    category: FileCategory.CODE,
    description: 'Безопасность и скорость. Любимец хакеров.',
    fullDescription: 'Современный системный язык. Гарантирует безопасность памяти без сборщика мусора. Самый любимый язык разработчиков по опросам StackOverflow.',
    osCompatibility: ['Cross-platform'],
    technologies: ['Borrow Checker', 'Zero-cost abstractions'],
    pros: ['Безопасность', 'Скорость C++'],
    cons: ['Очень высокий порог вхождения'],
    popularity: 85
  },
  {
    ext: '.ts',
    name: 'TypeScript',
    category: FileCategory.CODE,
    description: 'JavaScript с типами.',
    fullDescription: 'Надстройка над JS, добавляющая типы данных. Помогает избегать ошибок в больших проектах. Код компилируется в обычный JS.',
    osCompatibility: ['Web', 'Node.js'],
    technologies: ['Static Typing', 'Transpilation'],
    pros: ['Надежность', 'Автодополнение IDE'],
    cons: ['Нужна настройка сборки'],
    popularity: 95
  },
  {
    ext: '.swift',
    name: 'Swift',
    category: FileCategory.CODE,
    description: 'Язык для создания приложений Apple.',
    fullDescription: 'Современный, быстрый и безопасный язык от Apple для iOS и macOS. Заменил старый Objective-C.',
    osCompatibility: ['iOS', 'macOS'],
    technologies: ['LLVM', 'ARC'],
    pros: ['Удобство', 'Скорость'],
    cons: ['Только Apple (в основном)'],
    popularity: 70
  },

  // --- SYSTEM ---
  {
    ext: '.dll',
    name: 'Dynamic Link Library',
    category: FileCategory.SYSTEM,
    description: 'Библиотека Windows.',
    fullDescription: 'Кусок кода, который могут использовать разные программы одновременно. Экономит память.',
    osCompatibility: ['Windows'],
    technologies: ['Shared Library'],
    pros: ['Модульность'],
    cons: ['Конфликты версий ("DLL Hell")'],
    popularity: 90
  },
  {
    ext: '.sys',
    name: 'System File',
    category: FileCategory.SYSTEM,
    description: 'Драйвер или ядро.',
    fullDescription: 'Критически важный файл Windows. Часто это драйвер видеокарты или процессора. Не трогай его.',
    osCompatibility: ['Windows'],
    technologies: ['Kernel Mode'],
    pros: ['Низкоуровневый доступ'],
    cons: ['BSOD при ошибке'],
    popularity: 80
  },
  {
    ext: '.ini',
    name: 'Initialization File',
    category: FileCategory.SYSTEM,
    description: 'Настройки программ.',
    fullDescription: 'Простой текстовый файл с параметрами (Section -> Key = Value). Использовался в старых Windows и играх.',
    osCompatibility: ['Windows'],
    technologies: ['Plain Text'],
    pros: ['Легко править руками'],
    cons: ['Нет стандартов структуры'],
    popularity: 60
  },
  {
    ext: '.log',
    name: 'Log File',
    category: FileCategory.SYSTEM,
    description: 'Журнал событий.',
    fullDescription: 'Автоматически создаваемый файл, куда программа пишет все, что она делает. Нужен для поиска ошибок.',
    osCompatibility: ['Universal'],
    technologies: ['Append-only text'],
    pros: ['Помогает чинить баги'],
    cons: ['Может разрастись до гигабайтов'],
    popularity: 85
  },
  {
    ext: '.tmp',
    name: 'Temporary File',
    category: FileCategory.SYSTEM,
    description: 'Временный мусор.',
    fullDescription: 'Файл, созданный программой "на 5 минут" для промежуточных вычислений. Должен удаляться сам, но часто остается.',
    osCompatibility: ['Universal'],
    technologies: ['Cache'],
    pros: ['Ускоряет работу в моменте'],
    cons: ['Засоряет диск'],
    popularity: 50
  }
];

export const CATEGORY_COLORS: Record<FileCategory, string> = {
  [FileCategory.GAME]: 'text-orange-500 bg-orange-950/40 border-orange-500/30 shadow-[0_0_15px_-3px_rgba(249,115,22,0.3)]',
  [FileCategory.IMAGE]: 'text-cyan-400 bg-cyan-950/30 border-cyan-500/20 shadow-[0_0_15px_-3px_rgba(34,211,238,0.15)]',
  [FileCategory.AUDIO]: 'text-fuchsia-400 bg-fuchsia-950/30 border-fuchsia-500/20 shadow-[0_0_15px_-3px_rgba(232,121,249,0.15)]',
  [FileCategory.VIDEO]: 'text-violet-400 bg-violet-950/30 border-violet-500/20 shadow-[0_0_15px_-3px_rgba(167,139,250,0.15)]',
  [FileCategory.ARCHIVE]: 'text-amber-400 bg-amber-950/30 border-amber-500/20 shadow-[0_0_15px_-3px_rgba(251,191,36,0.15)]',
  [FileCategory.DOCUMENT]: 'text-emerald-400 bg-emerald-950/30 border-emerald-500/20 shadow-[0_0_15px_-3px_rgba(52,211,153,0.15)]',
  [FileCategory.EXECUTABLE]: 'text-rose-400 bg-rose-950/30 border-rose-500/20 shadow-[0_0_15px_-3px_rgba(251,113,133,0.15)]',
  [FileCategory.SYSTEM]: 'text-slate-400 bg-slate-900/50 border-slate-600/30 shadow-[0_0_15px_-3px_rgba(148,163,184,0.1)]',
  [FileCategory.CODE]: 'text-lime-400 bg-lime-950/30 border-lime-500/20 shadow-[0_0_15px_-3px_rgba(163,230,53,0.15)]',
};
